# HELP unbound_queries_total Total number of queries received.
# TYPE unbound_queries_total counter
unbound_queries_total 126561
# HELP unbound_queries_cookie_valid_total Total number of queries with a valid cookie.
# TYPE unbound_queries_cookie_valid_total counter
unbound_queries_cookie_valid_total 0
# HELP unbound_queries_cookie_client_total Total number of queries with a client cookie.
# TYPE unbound_queries_cookie_client_total counter
unbound_queries_cookie_client_total 0
# HELP unbound_cache_hits_total Total number of queries that were successfully answered using a cache lookup.
# TYPE unbound_cache_hits_total counter
unbound_cache_hits_total 97554
# HELP unbound_cache_misses_total Total number of cache queries that needed recursive processing.
# TYPE unbound_cache_misses_total counter
unbound_cache_misses_total 29007
# HELP unbound_prefetches_total Total number of cache prefetches performed.
# TYPE unbound_prefetches_total counter
unbound_prefetches_total 3600
# HELP unbound_expired_total Total number of expired entries served.
# TYPE unbound_expired_total counter
unbound_expired_total 242
# HELP unbound_recursive_replies_total Total number of replies sent to queries that needed recursive processing.
# TYPE unbound_recursive_replies_total counter
unbound_recursive_replies_total 28382
# HELP unbound_request_list_overwritten_total Total number of requests in the request list that were overwritten by newer entries.
# TYPE unbound_request_list_overwritten_total counter
unbound_request_list_overwritten_total 0
# HELP unbound_request_list_exceeded_total Number of queries that were dropped because the request list was full.
# TYPE unbound_request_list_exceeded_total counter
unbound_request_list_exceeded_total 619
# HELP unbound_request_list_current_all Current size of the request list, including internally generated queries.
# TYPE unbound_request_list_current_all gauge
unbound_request_list_current_all 6
# HELP unbound_request_list_current_user Current size of the request list, only counting the requests from client queries.
# TYPE unbound_request_list_current_user gauge
unbound_request_list_current_user 4
# HELP unbound_recursion_time_seconds_avg Average time it took to answer queries that needed recursive processing (does not include in-cache requests).
# TYPE unbound_recursion_time_seconds_avg gauge
unbound_recursion_time_seconds_avg 0.050564
# HELP unbound_recursion_time_seconds_median The median of the time it took to answer queries that needed recursive processing.
# TYPE unbound_recursion_time_seconds_median gauge
unbound_recursion_time_seconds_median 0.017362
# HELP unbound_time_now_seconds Current time in seconds since 1970.
# TYPE unbound_time_now_seconds gauge
unbound_time_now_seconds 1745256613.066916
# HELP unbound_time_up_seconds_total Uptime since server boot in seconds.
# TYPE unbound_time_up_seconds_total counter
unbound_time_up_seconds_total 2735.208062
# HELP unbound_time_elapsed_seconds Time since last statistics printout in seconds.
# TYPE unbound_time_elapsed_seconds counter
unbound_time_elapsed_seconds 2735.208062
# HELP unbound_memory_caches_bytes Memory in bytes in use by caches.
# TYPE unbound_memory_caches_bytes gauge
unbound_memory_caches_bytes{cache="rrset"} 12534253
unbound_memory_caches_bytes{cache="message"} 7983106
# HELP unbound_memory_modules_bytes Memory in bytes in use by modules.
# TYPE unbound_memory_modules_bytes gauge
unbound_memory_modules_bytes{module="iterator"} 16748
unbound_memory_modules_bytes{module="validator"} 1730677
unbound_memory_modules_bytes{module="respip"} 0
# HELP unbound_memory_doh_bytes Memory used by DoH buffers, in bytes.
# TYPE unbound_memory_doh_bytes gauge
unbound_memory_doh_bytes{buffer="query_buffer"} 0
unbound_memory_doh_bytes{buffer="response_buffer"} 0
# HELP unbound_response_time_seconds Query response time in seconds.
# TYPE unbound_response_time_seconds histogram
unbound_response_time_seconds_bucket{le="1e-06"} 4790
unbound_response_time_seconds_bucket{le="2e-06"} 4790
unbound_response_time_seconds_bucket{le="4e-06"} 4790
unbound_response_time_seconds_bucket{le="8e-06"} 4790
unbound_response_time_seconds_bucket{le="1.6e-05"} 4791
unbound_response_time_seconds_bucket{le="3.2e-05"} 4792
unbound_response_time_seconds_bucket{le="6.4e-05"} 4792
unbound_response_time_seconds_bucket{le="0.000128"} 4793
unbound_response_time_seconds_bucket{le="0.000256"} 4883
unbound_response_time_seconds_bucket{le="0.000512"} 5128
unbound_response_time_seconds_bucket{le="0.001024"} 5510
unbound_response_time_seconds_bucket{le="0.002048"} 6737
unbound_response_time_seconds_bucket{le="0.004096"} 7652
unbound_response_time_seconds_bucket{le="0.008192"} 9307
unbound_response_time_seconds_bucket{le="0.016384"} 13858
unbound_response_time_seconds_bucket{le="0.032768"} 19440
unbound_response_time_seconds_bucket{le="0.065536"} 24493
unbound_response_time_seconds_bucket{le="0.131072"} 26332
unbound_response_time_seconds_bucket{le="0.262144"} 27236
unbound_response_time_seconds_bucket{le="0.524288"} 27978
unbound_response_time_seconds_bucket{le="1"} 28244
unbound_response_time_seconds_bucket{le="2"} 28382
unbound_response_time_seconds_bucket{le="4"} 28382
unbound_response_time_seconds_bucket{le="8"} 28382
unbound_response_time_seconds_bucket{le="16"} 28382
unbound_response_time_seconds_bucket{le="32"} 28382
unbound_response_time_seconds_bucket{le="64"} 28382
unbound_response_time_seconds_bucket{le="128"} 28382
unbound_response_time_seconds_bucket{le="256"} 28382
unbound_response_time_seconds_bucket{le="512"} 28382
unbound_response_time_seconds_bucket{le="1024"} 28382
unbound_response_time_seconds_bucket{le="2048"} 28382
unbound_response_time_seconds_bucket{le="4096"} 28382
unbound_response_time_seconds_bucket{le="8192"} 28382
unbound_response_time_seconds_bucket{le="16384"} 28382
unbound_response_time_seconds_bucket{le="32768"} 28382
unbound_response_time_seconds_bucket{le="65536"} 28382
unbound_response_time_seconds_bucket{le="131072"} 28382
unbound_response_time_seconds_bucket{le="262144"} 28382
unbound_response_time_seconds_bucket{le="524288"} 28382
# HELP unbound_query_types_total Total number of queries with a given query type.
# TYPE unbound_query_types_total counter
unbound_query_types_total{type="A"} 70682
unbound_query_types_total{type="NS"} 110
unbound_query_types_total{type="CNAME"} 9
unbound_query_types_total{type="SOA"} 140
unbound_query_types_total{type="NULL"} 3
unbound_query_types_total{type="PTR"} 9860
unbound_query_types_total{type="MX"} 2435
unbound_query_types_total{type="TXT"} 2335
unbound_query_types_total{type="AAAA"} 35354
unbound_query_types_total{type="SRV"} 221
unbound_query_types_total{type="NAPTR"} 1
unbound_query_types_total{type="DS"} 116
unbound_query_types_total{type="DNSKEY"} 63
unbound_query_types_total{type="SVCB"} 61
unbound_query_types_total{type="HTTPS"} 5163
unbound_query_types_total{type="other"} 8
# HELP unbound_query_classes_total Total number of queries with a given query class.
# TYPE unbound_query_classes_total counter
unbound_query_classes_total{class="IN"} 126561
# HELP unbound_query_opcodes_total Total number of queries with a given query opcode.
# TYPE unbound_query_opcodes_total counter
unbound_query_opcodes_total{opcode="QUERY"} 126561
# HELP unbound_query_tcp_total Total number of queries that were made using TCP towards the Unbound server, including DoT and DoH queries.
# TYPE unbound_query_tcp_total counter
unbound_query_tcp_total 783
# HELP unbound_query_tcpout_total Total number of queries that the Unbound server made using TCP outgoing towards other servers.
# TYPE unbound_query_tcpout_total counter
unbound_query_tcpout_total 191
# HELP unbound_query_udpout_total Total number of queries that the Unbound server made using UDP outgoing towards￼other servers.
# TYPE unbound_query_udpout_total counter
unbound_query_udpout_total 122776
# HELP unbound_query_tls_total Total number of queries that were made using TCP TLS towards the Unbound server, including DoT and DoH queries.
# TYPE unbound_query_tls_total counter
unbound_query_tls_total 0
# HELP unbound_query_tls_resume_total Total number of queries that were made using TCP TLS Resume towards the Unbound server.
# TYPE unbound_query_tls_resume_total counter
unbound_query_tls_resume_total 0
# HELP unbound_query_ipv6_total Total number of queries that were made using IPv6 towards the Unbound server.
# TYPE unbound_query_ipv6_total counter
unbound_query_ipv6_total 2736
# HELP unbound_query_https_total Total number of DoH queries that were made towards the Unbound server.
# TYPE unbound_query_https_total counter
unbound_query_https_total 0
# HELP unbound_query_flags_total Total number of queries that had a given flag set in the header.
# TYPE unbound_query_flags_total counter
unbound_query_flags_total{flag="QR"} 0
unbound_query_flags_total{flag="AA"} 0
unbound_query_flags_total{flag="TC"} 0
unbound_query_flags_total{flag="RD"} 126561
unbound_query_flags_total{flag="RA"} 14
unbound_query_flags_total{flag="Z"} 0
unbound_query_flags_total{flag="AD"} 3832
unbound_query_flags_total{flag="CD"} 330
# HELP unbound_query_edns_present_total Total number of queries that had an EDNS OPT record present.
# TYPE unbound_query_edns_present_total counter
unbound_query_edns_present_total 25374
# HELP unbound_query_edns_DO_total Total number of queries that had an EDNS OPT record with the DO (DNSSEC OK) bit set present.
# TYPE unbound_query_edns_DO_total counter
unbound_query_edns_DO_total 4966
# HELP unbound_answer_rcodes_total Total number of answers to queries, from cache or from recursion, by response code.
# TYPE unbound_answer_rcodes_total counter
unbound_answer_rcodes_total{rcode="NOERROR"} 115327
unbound_answer_rcodes_total{rcode="FORMERR"} 0
unbound_answer_rcodes_total{rcode="SERVFAIL"} 558
unbound_answer_rcodes_total{rcode="NXDOMAIN"} 10051
unbound_answer_rcodes_total{rcode="NOTIMPL"} 0
unbound_answer_rcodes_total{rcode="REFUSED"} 0
unbound_answer_rcodes_total{rcode="nodata"} 18876
# HELP unbound_answers_secure_total Total number of answers that were secure.
# TYPE unbound_answers_secure_total counter
unbound_answers_secure_total 66883
# HELP unbound_answers_bogus Total number of answers that were bogus.
# TYPE unbound_answers_bogus counter
unbound_answers_bogus 0
# HELP unbound_rrset_bogus_total Total number of rrsets marked bogus by the validator.
# TYPE unbound_rrset_bogus_total counter
unbound_rrset_bogus_total 0
# HELP unbound_query_aggressive_nsec Total number of queries that the Unbound server generated response using Aggressive NSEC.
# TYPE unbound_query_aggressive_nsec counter
unbound_query_aggressive_nsec{rcode="NOERROR"} 1039
unbound_query_aggressive_nsec{rcode="NXDOMAIN"} 147
# HELP unbound_unwanted_queries_total Total number of queries that were refused or dropped because they failed the access control settings.
# TYPE unbound_unwanted_queries_total counter
unbound_unwanted_queries_total 0
# HELP unbound_unwanted_replies_total Total number of replies that were unwanted or unsolicited.
# TYPE unbound_unwanted_replies_total counter
unbound_unwanted_replies_total 0
# HELP unbound_msg_cache_count The Number of Messages cached
# TYPE unbound_msg_cache_count gauge
unbound_msg_cache_count 23967
# HELP unbound_rrset_cache_count The Number of rrset cached
# TYPE unbound_rrset_cache_count gauge
unbound_rrset_cache_count 33521
# HELP unbound_msg_cache_max_collisions_total Total number of msg cache hashtable collisions.
# TYPE unbound_msg_cache_max_collisions_total counter
unbound_msg_cache_max_collisions_total 6
# HELP unbound_rrset_cache_max_collisions_total Total number of rrset cache hashtable collisions.
# TYPE unbound_rrset_cache_max_collisions_total counter
unbound_rrset_cache_max_collisions_total 7
unbound_response_time_seconds_bucket{le="+Inf"} 28382
unbound_response_time_seconds_count 28382
unbound_response_time_seconds_sum 1435.107448
# HELP unbound_up Whether scraping Unbound metrics was successful.
# TYPE unbound_up gauge
unbound_up 1
